import type { Metadata } from "next";
import Header from "../components/Header";


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <div className="flex flex-col">
           <div className=""> 
            
            <Header/>
            </div>
           <div className="w-full">{children}</div>
        </div>
       
      </body>
    </html>
  );
}
